config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount ActionCable.server => '/cable'
  authenticated :user, -> user { user.admin? }  do
    mount Flipflop::Engine => "/flipflop"
    mount DelayedJobWeb, at: "/delayed_job"
  end

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    confirmations: 'users/confirmations',
                                    unlocks: 'users/unlocks',
                                    passwords: 'users/passwords' }

  authenticated do
    root to: "home#dashboard", as: :authenticated_root
  end

  root to: redirect('/users/sign_in')

  get 'v2', to: 'home#design2'

  get '/home', to: 'home#dashboard'

  namespace :api do
    namespace :v1 do
      get 'referral_bounces/refer'
      get 'docs/swagger.:format', to: "swagger#index"
      get 'docs', to: "swagger#apidocs"
      resources :leads, only: [:index, :create ]
      get 'leads/prospect_stats', to: "leads#prospect_stats"
      get 'property_info', to: "leads#property_info"
      get 'property_schedule_availability.:format', to: "leads#property_schedule_availability"
      resources :messages, only: [:create]
    end
  end

  resources :scheduled_actions do
    collection do
      get :conflict_check, to: 'scheduled_actions#conflict_check'
      get 'update_scheduled_action_form_on_action_change', to: 'scheduled_actions#update_scheduled_action_form_on_action_change'
      get 'load_notification_template', to: 'scheduled_actions#load_notification_template'
    end
    member do
      post 'complete', to: 'scheduled_actions#complete'
      get 'completion_form', to: 'scheduled_actions#completion_form'
    end
  end

  resources :lead_actions
  resources :lead_referral_sources
  resources :articles
  resources :notes
  resources :reasons
  resources :roles
  resources :unit_types
  resources :units
  resources :users do
    member do
      post 'switch_setting', to: 'users#switch_setting'
    end
  end
  resources :residents
  resources :engagement_policies

  resources :properties do
    resources :units
    resources :unit_types
    resources :residents
    resource :messages, controller: 'property_messages', only: [:edit, :update] do
      member do
        post 'preview_sms'
        post 'preview_email'
      end
    end
    collection do
      post 'select_current', to: 'properties#select_current'
    end
    member do
      get 'duplicate_leads', to: 'properties#duplicate_leads'
      get 'user_stats', to: 'properties#user_stats'
    end
  end

  resources :leads do
    collection do
      get 'new/:entry', to: 'leads#new', as: 'custom_new'
      get 'search', to: "leads#search"
      get 'status_dashboard', to: "leads#status_dashboard"
      get 'mass_assignment', to: 'leads#mass_assignment'
      post 'mass_assign', to: 'leads#mass_assign'
    end
    member do
      post 'trigger_state_event', to: "leads#trigger_state_event"
      post 'mark_messages_read', to: "leads#mark_messages_read"
      get 'progress_state', to: "leads#progress_state"
      post 'update_state', to: "leads#update_state"
      get 'update_referrable_options', to: 'leads#update_referrable_options'
      post 'resend_sms_opt_in_message', to: 'leads#resend_sms_opt_in_message'
      post 'update_from_remote', to: 'leads#update_from_remote'
    end
    resources :messages do
      post 'deliver', on: :member
      post 'mark_read', on: :member
      post 'lead_page_mark_read', on: :member
    end
    resources :roommates
  end

  resources :lead_sources do
    post 'reset_token', on: :member
  end

  resources :messages do
    post 'deliver', on: :member
    post 'mark_read', on: :member
    get 'body_preview', on: :member
  end

  resources :message_templates

  resources :marketing_sources do
    resources :marketing_expenses
    collection do
      get 'form_suggest_tracking_details', to: 'marketing_sources#form_suggest_tracking_details'
      get 'report', to: 'marketing_sources#report'
    end
  end

  namespace :stats do
    get 'manager', to: 'manager'
    get 'report_csv', to: 'report_csv'
    get 'lead_engagement_csv', to: 'lead_engagement_csv'
    get 'referral_bounces', to: 'referral_bounces'
  end

  namespace :home do
    get 'manager_dashboard', to: 'manager_dashboard'
    get 'dashboard', to: 'dashboard'
    get 'insert_open_lead', to: 'insert_open_lead'
    post 'impersonate', to: 'impersonate'
    post 'end_impersonation', to: 'end_impersonation'
  end

  resources :teams do
    member do
      post 'add_member', to: 'add_member'
    end
  end

  get '/messaging/preferences', to: 'home#messaging_preferences', as: 'messaging_preferences'
  post '/messaging/unsubscribe', to: 'home#unsubscribe', as: 'messaging_unsubscribe'

end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id          :uuid             not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Team < ApplicationRecord
  audited
  include Teams::TeamUsers
  include Seeds::Seedable

  ### Constants
  ALLOWED_PARAMS = [:name, :description]

  ### Associations
  has_many :properties
  has_many :leads, through: :properties

  ### Validations
  validates :name, presence: true, uniqueness: true
end

app/models/teamrole.rb
# == Schema Information
#
# Table name: teamroles
#
#  id          :uuid             not null, primary key
#  name        :string
#  slug        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Teamrole < ApplicationRecord
  ### Class Concerns/Extensions
  include Comparable
  audited

  ### Constants
  ALLOWED_PARAMS = [:id, :name, :slug, :description]
  HIERARCHY = [ :lead, :agent, :none]

  ### Validations
  validates :name, :slug,
    presence: true, uniqueness: true

  ### Associations
  has_many :users

  ### Class Methods

  def self.agent
    self.where(slug: 'agent').first
  end

  def self.manager
    raise "Manager Teamrole is deprecated"
    #self.where(slug: 'manager').first
  end

  def self.lead
    self.where(slug: 'lead').first
  end

  def self.none
    self.where(slug: 'none').first
  end

  ### Instance Methods

  def <=>(other)
    return 1 if other.nil?
    return 1 if HIERARCHY.index(other.slug&.to_sym).nil?
    return -1 if HIERARCHY.index(slug.to_sym).nil?
    return HIERARCHY.index(other.slug.to_sym) <=> HIERARCHY.index(slug.to_sym)
  end

  def agent?
    slug == 'agent'
  end

  def manager?
    raise "Manager Teamrole is deprecated"
    #slug == 'manager'
  end

  def lead?
    slug == 'lead'
  end

  def none?
    slug == 'none'
  end

end

app/views/shared/_appsettings.html.erb
<% if current_user&.profile %>
  <%= tooltip_block('toggle-message-notifications') do %>
    <div class="sidebar__account-controls-button toggle-setting__button <%= current_user&.profile&.setting_enabled?(:message_web_notifications) ? 'toggle-setting__button--on' : 'toggle-setting__button--off' %>" id="toggle_message_notifications">
      <%= link_to(switch_setting_user_path(id: current_user.id, setting: :message_web_notifications), method: :post) do %>
        <span class="glyphicon glyphicon-envelope"></span>
      <% end %>
    </div>
  <% end %>

  <%= tooltip_block('toggle-lead-notifications') do %>
    <div class="sidebar__account-controls-button toggle-setting__button <%= current_user&.profile&.setting_enabled?(:lead_web_notifications) ? 'toggle-setting__button--on' : 'toggle-setting__button--off' %>" id="toggle_lead_notifications">
      <%= link_to(switch_setting_user_path(id: current_user.id, setting: :lead_web_notifications), method: :post) do %>
        <span class="glyphicon glyphicon-flag"></span>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_browser_check.html.erb
<script> 
  var $buoop = {required:{e:-4,f:-3,o:-3,s:-1,c:-3},insecure:true,unsupported:true,api:2019.07 }; 
  function $buo_f(){ 
    var e = document.createElement("script"); 
    e.src = "browser-update.org.min.js"; 
    document.body.appendChild(e);
  };
  try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
  catch(e){window.attachEvent("onload", $buo_f)}
</script>

app/views/shared/_editor_init.html.erb
<script>
  window.init_html_editor_v2 = function () {
    window.html_editor_v2 = new FroalaEditor(
      '#html_editor_v2',
      {
        key: 'cJC7bA5B2G2A2B2I2yQNDMIJg1IQNSEa1EUAi1XVFQd1EaG3C2A5D5C4E3F3D4G2B2==',
        imageUploadToS3: <%= editor_aws_data.to_json.html_safe %>,
        fileUploadToS3: <%= editor_aws_data.to_json.html_safe %>
      }
    );
  }

  window.destroy_html_editor_v2 = function() {
    console.log('destroying...');
    window.html_editor_v2.destroy();
  }

  $(document).on('turbolinks:load',function(){
    window.init_html_editor_v2();
  });
</script>

app/views/shared/_enabled_features.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <strong>Site Features: </strong>
    <% UserProfile.managed_features.each do |feature| %>
      <span class="btn btn--small btn-<%= Flipflop.enabled?(feature) ? 'success' : 'default' %>">
        <%= feature %>
      </span>
    <% end %>
  </div>
</div>

app/views/shared/_html_head.html.erb
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<meta name="description" content="Bluesky Lead Management for Bluecrest Residential" />
<%= render partial: "shared/favicon" %>
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="msapplication-config" content="browserconfig.xml" />

app/views/shared/_impersonation.html.erb
<% if impersonating? %>
<div class="row">
  <div class="col-md-12">
    Impersonating <%= current_user.name %> (<%= current_user.email %>) 
    <%= link_to('EXIT', home_end_impersonation_path, method: :post) %>
  </div>
</div>
<% end %>

app/views/shared/_navbar_v1.html.erb
<% if current_user %>
<div id="sidebar">
  <div id="sidebar--top-actions">
    <div class="sidebar--action-button">
      <%= link_to(custom_new_leads_path(entry: 'walkin')) do %>
        <%= image_tag('/icons/walkin.svg') %>
        <span class="sidebar--action-button--label">New Walk-In</span>
      <% end %>
    </div>
    <div class="sidebar--action-button">
      <%= link_to(new_scheduled_action_path) do %>
        <%= image_tag('/icons/new_task.svg') %>
        <span class="sidebar--action-button--label">New Task</span>
      <% end %>
    </div>
  </div>

  <div class="sidebar--header"> </div>
  <div class="sidebar--item-group">
    <div class="sidebar--item <%= nav_item_class(:home) %>">
      <%= link_to(root_path) do %>
        <%= image_tag('/icons/home.svg') %>
        <span class="sidebar--item-content">Home</span>
      <% end %>
    </div>
    <div class="sidebar--item <%= nav_item_class(:messages) %>">
      <%= link_to(messages_path) do %>
        <%= image_tag('/icons/messages.svg') %>
        <span class="sidebar--item-content">Messages</span>
      <% end %>
      <% if current_user.messages.for_leads.relevant_to_leads.incoming.unread.any? %>
        <span class="sidebar--item-alert">&#9679;</span>
      <% end %>
    </div>
    <div class="sidebar--item <%= nav_item_class(:scheduled_actions) %>">
      <%= link_to(scheduled_actions_path(team: true)) do %>
        <%= image_tag('/icons/calendar.svg') %>
        <span class="sidebar--item-content">Calendar</span>
      <% end %>
      <% if current_user.scheduled_actions.incomplete.any? %>
        <span class="sidebar--item-alert">&#9679;</span>
      <% end %>
    </div>
  </div>

  <div class="sidebar--header">
    Leads
  </div>
  <div class="sidebar--item-group">
    <div class="sidebar--item <%= nav_item_class(:leads, :search) %>">
      <%= link_to(search_leads_path(lead_search: {states: ['open']})) do %>
        <%= image_tag('/icons/open_folder.svg') %>
        <span class="sidebar--item-content">Open</span>
      <% end %>
      <% if ( (@property || @current_property).leads.open.any? rescue false ) %>
        <span class="sidebar--item-alert">&#9679;</span>
      <% end %>
    </div>
    <div class="sidebar--item <%= nav_item_class(:leads, :search) %>">
      <%= link_to(search_leads_path(lead_search: {user_ids: [current_user.id], states: Lead::IN_PROGRESS_STATES})) do %>
        <%= image_tag('/icons/star.svg') %>
        <span class="sidebar--item-content">Mine</span>
      <% end %>
    </div>
    <div class="sidebar--item <%= nav_item_class(:leads, :search) %>">
      <%= link_to(search_leads_path) do %>
        <%= image_tag('/icons/magnifying_glass.svg') %>
        <span class="sidebar--item-content">All</span>
      <% end %>
    </div>
    <div class="sidebar--item <%= nav_item_class(:leads, :search) %>">
      <%= link_to(search_leads_path(lead_search: {states: ['waitlist']})) do %>
        <%= image_tag('/icons/hourglass.svg') %>
        <span class="sidebar--item-content">Waitlist</span>
      <% end %>
    </div>
    <% if policy(Lead).mass_assignment? %>
      <div class="sidebar--item <%= nav_item_class(:leads, :mass_assignment) %>">
        <%= link_to(mass_assignment_leads_path) do %>
          <%= image_tag('/icons/pencil_assign.svg') %>
          <span class="sidebar--item-content">Assign Leads</span>
        <% end %>
      </div>
    <% end %>
    <div class="sidebar--item <%= nav_item_class(:stats, :manager) %>">
      <%= link_to(stats_manager_path(filter: true, date_range: [ 'month' ], property_ids: [ @current_property&.id ])) do %>
        <%= image_tag('/icons/chart.svg') %>
        <span class="sidebar--item-content">Analytics</span>
      <% end %>
    </div>
    <div class="sidebar--item <%= nav_item_class(:leads, :status_dashboard) %>">
      <%= link_to(status_dashboard_leads_path) do %>
        <%= image_tag('/icons/chart.svg') %>
        <span class="sidebar--item-content">Status Dashboard</span>
      <% end %>
    </div>
  </div>


  <div class="sidebar--header">Property</div>
  <div class="sidebar--item-group">
    <% if ( policy(@property || @current_property).show? rescue false ) %>
      <div class="sidebar--item <%= nav_item_class(:properties, :show) %>">
        <%= link_to(property_path(@property || @current_property)) do %>
          <%= image_tag('/icons/building.svg') %>
          <span class="sidebar--item-content">This Property</span>
        <% end %>
      </div>
    <% end if (@property || @current_property)&.id %>
    <% if policy(Property).index? %>
      <div class="sidebar--item <%= nav_item_class(:properties, :index) %>">
        <%= link_to(properties_path) do %>
          <%= image_tag('/icons/buildings.svg') %>
          <span class="sidebar--item-content">All Properties</span>
        <% end %>
      </div>
    <% end %>
    <% if policy(Unit).index? %>
      <div class="sidebar--item <%= nav_item_class(:units) %>">
        <%= link_to(units_path) do %>
          <%= image_tag('/icons/units.svg') %>
          <span class="sidebar--item-content">Units</span>
        <% end %>
      </div>
    <% end %>
    <% if ( current_user.admin? || current_user.manager? ) && policy(UnitType).index? %>
      <div class="sidebar--item <%= nav_item_class(:unit_types) %>">
        <%= link_to(unit_types_path) do %>
          <%= image_tag('/icons/unit_types.svg') %>
          <span class="sidebar--item-content">Unit Types</span>
        <% end %>
      </div>
    <% end %>
    <% if policy(MarketingSource).index? %>
      <div class="sidebar--item <%= nav_item_class(:marketing_sources) %>">
        <%= link_to(marketing_sources_path) do %>
          <%= image_tag('/icons/marketing.svg') %>
          <span class="sidebar--item-content">Marketing</span>
        <% end %>
      </div>
    <% end %>
    <% if ( current_user.admin? || current_user.manager? ) && policy(Team).index? %>
      <div class="sidebar--item <%= nav_item_class(:teams) %>">
        <%= link_to(teams_path) do %>
          <%= image_tag('/icons/teams.svg') %>
          <span class="sidebar--item-content">Teams</span>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="sidebar--header">Manage</div>
  <div class="sidebar--item-group">
    <% if current_user.admin? || current_user.manager? %>
    <% if policy(User).index? %>
      <div class="sidebar--item <%= nav_item_class(:users, :index) %>">
        <%= link_to(users_path) do %>
          <%= image_tag('/icons/users.svg') %>
          <span class="sidebar--item-content">Users</span>
        <% end %>
      </div>
    <% end %>
    <% if policy(Role).index? %>
      <div class="sidebar--item <%= nav_item_class(:roles) %>">
        <%= link_to(roles_path) do %>
          <%= image_tag('/icons/user_roles.svg') %>
          <span class="sidebar--item-content">User Roles</span>
        <% end %>
      </div>
    <% end %>
    <% if policy(EngagementPolicy).index? %>
      <div class="sidebar--item <%= nav_item_class(:engagement_policies) %>">
        <%= link_to(engagement_policies_path) do %>
          <%= image_tag('/icons/engagement.svg') %>
          <span class="sidebar--item-content">Policies</span>
        <% end %>
      </div>
    <% end %>
    <% if policy(LeadSource).index? %>
      <div class="sidebar--item <%= nav_item_class(:lead_sources) %>">
        <%= link_to(lead_sources_path) do %>
          <%= image_tag('/icons/lead_sources.svg') %>
          <span class="sidebar--item-content">Lead Sources</span>
        <% end %>
      </div>
    <% end %>
    <% if policy(LeadReferralSource).edit? %>
      <div class="sidebar--item <%= nav_item_class(:lead_referral_sources) %>">
        <%= link_to(lead_referral_sources_path) do %>
          <%= image_tag('/icons/referral_sources.svg') %>
          <span class="sidebar--item-content">Referral Sources</span>
        <% end %>
      </div>
    <% end %>
    <% if policy(LeadAction).index? %>
      <div class="sidebar--item <%= nav_item_class(:lead_actions) %>">
        <%= link_to(lead_actions_path) do %>
          <%= image_tag('/icons/lead_actions.svg') %>
          <span class="sidebar--item-content">Lead Actions</span>
        <% end %>
      </div>
    <% end %>
    <% if policy(Reason).index? %>
      <div class="sidebar--item <%= nav_item_class(:reasons) %>">
        <%= link_to(reasons_path) do %>
          <%= image_tag('/icons/reasons.svg') %>
          <span class="sidebar--item-content">Reasons</span>
        <% end %>
      </div>
    <% end %>
    <% end %>
    <% if policy(MessageTemplate).index? %>
      <div class="sidebar--item <%= nav_item_class(:message_templates) %>">
        <%= link_to(message_templates_path) do %>
          <%= image_tag('/icons/templates.svg') %>
          <span class="sidebar--item-content">Templates</span>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="sidebar--header"></div>
  <div class="sidebar--item-group">
    <div class="sidebar--item <%= nav_item_class(:articles) %>">
      <%= link_to(current_page_help_path, method: :get) do %>
        <%= image_tag('/icons/help.svg') %>
        <span class="sidebar--item-content">Help</span>
      <% end %>
    </div>
    <div class="sidebar--item <%= nav_item_class(:articles) %>">
      <a href="#" onclick="alert('Please use Slack\'s Request form in the #bluesky-support channel to submit support requests.'); return false;">
        <%= image_tag('/icons/help.svg') %>
        <span class="sidebar--item-content">Support Ticket</span>
      </a>
    </div>
    <div class="sidebar--item">
      <%= link_to(destroy_user_session_path, method: :delete) do %>
        <%= image_tag('/icons/logout.svg') %>
        <span class="sidebar--item-content">Logout</span>
      <% end %>
    </div>
  </div>

  <div id="sidebar--account-controls">
    <div class="sidebar--account-controls--buttons">
      <div class="sidebar--account-controls--button">
        <%= link_to(edit_user_path(current_user), method: :get) do %>
        <%= image_tag('/icons/gear.svg') %>
        <% end %>
      </div>
      <div class="sidebar--account-controls--button sidebar--account-controls--profile">
        <% if @current_user&.profile&.photo.present? %>
          <%= image_tag(@current_user.profile.photo.variant(resize: "50x"), alt: "#{@current_user.name || 'User'} photo" )%>
        <% else %>
          <%= @current_user.initials %>
        <% end %>
      </div>
      <div class="sidebar--account-controls--button" style="padding-left: 20px;">
        <%= render partial: 'shared/appsettings' %>
      </div>
    </div>
    <span class="sidebar--account-controls--username">
      <%= @current_user.email %>
    </span>
    <br/>
    <br/>
    <%= image_tag('bluecrest-logo.svg') %>
    <br />
  </div>
</div>
<% end %>

app/views/shared/_notifications.html.erb
<div id="notifications">
  <div class="row">
    <div class="col-md-12 text-center">
      <% if notice.present? %>
        <p class="notice bg-warning"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert bg-danger"><%= alert %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_property_selection.html.erb
<% if policy(Property).select_current? %>
  <%= form_tag(select_current_properties_path, method: :post, remote: false, id: 'propertyselection--form', class: 'property-selection-inline') do %>
    <div id="propertyselection--container" class="property-selection-container">
      <label for="propertyselection--selector" class="property-selection-label">
        <%= glyph(:home) %> Property:
      </label>
      <%= select_tag :property_id, property_options_for_current(@current_property&.id), id: 'propertyselection--selector', class: "form__control property-selection-select" %>
      <%= submit_tag 'Select', id: 'propertyselection--submit-button', class: 'btn btn--primary btn--small property-selection-button hidden' %>
    </div>
  <% end %>

  <script>
    document.getElementById('propertyselection--selector').
      addEventListener('change', function(e){ $('#propertyselection--submit-button').removeClass('hidden') });
  </script>
<% end %>

app/views/shared/_property_selection_v2.html.erb
<% if policy(Property).select_current? %>
  <div id="header-property-selector">
    <%= form_tag(select_current_properties_path, method: :post, remote: false, id: 'propertyselection--form', class: 'form-inline') do %>
      <%= select_tag :property_id, property_options_for_current(@current_property&.id), id: 'propertyselection--selector', class: "form-control form-control-sm", prompt: '-- Select One --', allow_blank: false %>
    <% end %>
  </div>
  <script type='text/javascript'>
    document.getElementById('propertyselection--selector').
      addEventListener('change', function(e){ 
        var val = e.target.options[e.target.selectedIndex].text
        if (val != '-- Select One --')  { 
          $('#propertyselection--form').submit()
        }
      });
      /*
    document.getElementById('header-property-selection-toggle').
      addEventListener('mouseup', function(e){
        e.preventDefault();
        var selector = document.getElementById('propertyselection--selector')
        if (selector.style.display == "none") {
          selector.style.display = "block"
        } else {
          selector.style.display = "none"
        } 
      });
      */
  </script>
<% end %>

app/views/shared/_trackjs.html.erb
<script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
<script>
  window.TrackJS && TrackJS.install({
    token: "b23b23e1d5cc4cf0b4912e0b1b601104",
    application: "bluesky-<%= Rails.env %>"
  });
</script>

app/views/shared/ripple_loader.html.erb
<div id="ripple-loader"><div></div><div></div></div>