config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount ActionCable.server => '/cable'
  authenticated :user, -> user { user.admin? }  do
    mount Flipflop::Engine => "/flipflop"
    mount DelayedJobWeb, at: "/delayed_job"
  end

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    confirmations: 'users/confirmations',
                                    unlocks: 'users/unlocks',
                                    passwords: 'users/passwords' }

  authenticated do
    root to: "home#dashboard", as: :authenticated_root
  end

  root to: redirect('/users/sign_in')

  get 'v2', to: 'home#design2'

  get '/home', to: 'home#dashboard'

  namespace :api do
    namespace :v1 do
      get 'referral_bounces/refer'
      get 'docs/swagger.:format', to: "swagger#index"
      get 'docs', to: "swagger#apidocs"
      resources :leads, only: [:index, :create ]
      get 'leads/prospect_stats', to: "leads#prospect_stats"
      get 'property_info', to: "leads#property_info"
      get 'property_schedule_availability.:format', to: "leads#property_schedule_availability"
      resources :messages, only: [:create]
    end
  end

  resources :scheduled_actions do
    collection do
      get :conflict_check, to: 'scheduled_actions#conflict_check'
      get 'update_scheduled_action_form_on_action_change', to: 'scheduled_actions#update_scheduled_action_form_on_action_change'
      get 'load_notification_template', to: 'scheduled_actions#load_notification_template'
    end
    member do
      post 'complete', to: 'scheduled_actions#complete'
      get 'completion_form', to: 'scheduled_actions#completion_form'
    end
  end

  resources :lead_actions
  resources :lead_referral_sources
  resources :articles
  resources :notes
  resources :reasons
  resources :roles
  resources :unit_types
  resources :units
  resources :users do
    member do
      post 'switch_setting', to: 'users#switch_setting'
    end
  end
  resources :residents
  resources :engagement_policies

  resources :properties do
    resources :units
    resources :unit_types
    resources :residents
    resource :messages, controller: 'property_messages', only: [:edit, :update] do
      member do
        post 'preview_sms'
        post 'preview_email'
      end
    end
    collection do
      post 'select_current', to: 'properties#select_current'
    end
    member do
      get 'duplicate_leads', to: 'properties#duplicate_leads'
      get 'user_stats', to: 'properties#user_stats'
    end
  end

  resources :leads do
    collection do
      get 'new/:entry', to: 'leads#new', as: 'custom_new'
      get 'search', to: "leads#search"
      get 'status_dashboard', to: "leads#status_dashboard"
      get 'mass_assignment', to: 'leads#mass_assignment'
      post 'mass_assign', to: 'leads#mass_assign'
    end
    member do
      post 'trigger_state_event', to: "leads#trigger_state_event"
      post 'mark_messages_read', to: "leads#mark_messages_read"
      get 'progress_state', to: "leads#progress_state"
      post 'update_state', to: "leads#update_state"
      get 'update_referrable_options', to: 'leads#update_referrable_options'
      post 'resend_sms_opt_in_message', to: 'leads#resend_sms_opt_in_message'
      post 'update_from_remote', to: 'leads#update_from_remote'
    end
    resources :messages do
      post 'deliver', on: :member
      post 'mark_read', on: :member
      post 'lead_page_mark_read', on: :member
    end
    resources :roommates
  end

  resources :lead_sources do
    post 'reset_token', on: :member
  end

  resources :messages do
    post 'deliver', on: :member
    post 'mark_read', on: :member
    get 'body_preview', on: :member
  end

  resources :message_templates

  resources :marketing_sources do
    resources :marketing_expenses
    collection do
      get 'form_suggest_tracking_details', to: 'marketing_sources#form_suggest_tracking_details'
      get 'report', to: 'marketing_sources#report'
    end
  end

  namespace :stats do
    get 'manager', to: 'manager'
    get 'report_csv', to: 'report_csv'
    get 'lead_engagement_csv', to: 'lead_engagement_csv'
    get 'referral_bounces', to: 'referral_bounces'
  end

  namespace :home do
    get 'manager_dashboard', to: 'manager_dashboard'
    get 'dashboard', to: 'dashboard'
    get 'insert_open_lead', to: 'insert_open_lead'
    post 'impersonate', to: 'impersonate'
    post 'end_impersonation', to: 'end_impersonation'
  end

  resources :teams do
    member do
      post 'add_member', to: 'add_member'
    end
  end

  get '/messaging/preferences', to: 'home#messaging_preferences', as: 'messaging_preferences'
  post '/messaging/unsubscribe', to: 'home#unsubscribe', as: 'messaging_unsubscribe'

end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id          :uuid             not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Team < ApplicationRecord
  audited
  include Teams::TeamUsers
  include Seeds::Seedable

  ### Constants
  ALLOWED_PARAMS = [:name, :description]

  ### Associations
  has_many :properties
  has_many :leads, through: :properties

  ### Validations
  validates :name, presence: true, uniqueness: true
end

app/models/teamrole.rb
# == Schema Information
#
# Table name: teamroles
#
#  id          :uuid             not null, primary key
#  name        :string
#  slug        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Teamrole < ApplicationRecord
  ### Class Concerns/Extensions
  include Comparable
  audited

  ### Constants
  ALLOWED_PARAMS = [:id, :name, :slug, :description]
  HIERARCHY = [ :lead, :agent, :none]

  ### Validations
  validates :name, :slug,
    presence: true, uniqueness: true

  ### Associations
  has_many :users

  ### Class Methods

  def self.agent
    self.where(slug: 'agent').first
  end

  def self.manager
    raise "Manager Teamrole is deprecated"
    #self.where(slug: 'manager').first
  end

  def self.lead
    self.where(slug: 'lead').first
  end

  def self.none
    self.where(slug: 'none').first
  end

  ### Instance Methods

  def <=>(other)
    return 1 if other.nil?
    return 1 if HIERARCHY.index(other.slug&.to_sym).nil?
    return -1 if HIERARCHY.index(slug.to_sym).nil?
    return HIERARCHY.index(other.slug.to_sym) <=> HIERARCHY.index(slug.to_sym)
  end

  def agent?
    slug == 'agent'
  end

  def manager?
    raise "Manager Teamrole is deprecated"
    #slug == 'manager'
  end

  def lead?
    slug == 'lead'
  end

  def none?
    slug == 'none'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :messaging_preferences, :unsubscribe]

  def dashboard
    authorize User, policy_class: HomePolicy
    @page_title = "Bluesky Dashboard"

    @my_leads = Lead.for_agent(current_user).in_progress.is_lead.includes(:source)
    @open_leads = current_user.available_leads(@current_property&.leads).includes(:property, :source)
    @today_actions = ScheduledAction.includes(:schedule, :lead_action, :target).for_agent(current_user).due_today.sorted_by_due_asc
    @upcoming_actions = ScheduledAction.includes(:schedule, :lead_action).for_agent(current_user).upcoming.sorted_by_due_asc
    @limit_leads = [ ( params[:limit_leads] || 5 ).to_i,  @open_leads.count ].min
  end

  def design2
    @page_title = "Bluesky Dashboardv2"
  end

  def manager_dashboard
    authorize User, policy_class: HomePolicy
    @page_title = "Manager Dashboard"
  end

  def messaging_preferences
    authorize User, policy_class: HomePolicy
    @page = "Update Messaging Preferences"
    @lead = Lead.where(id: params[:id]).first
  end

  def unsubscribe
    authorize User, policy_class: HomePolicy
    @page = "Update Messaging Preferences"
    lead_id = params[:lead_id]
    email_optout = params[:lead_email_optout]
    sms_optout = params[:lead_sms_optout]
    @lead = Lead.find(lead_id)
    if email_optout == "true"
      @lead.optout_email!
    else
      @lead.optin_email!
    end
    if sms_optout == "true"
      @lead.optout_sms!
    else
      @lead.optin_sms!
    end
  end

  def insert_open_lead
    authorize User, policy_class: HomePolicy
    @lead = current_user.available_leads.find(params[:id])
  end

  def impersonate
    @target_user = User.find(params[:id])
    authorize @target_user

    impersonate_user(@target_user)
    redirect_to root_path
  end

  def end_impersonation
    terminate_impersonation
    redirect_to root_path
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_active_leads_all_leads.html.erb
<div class="active-leads-pane tab-pane fade" id="all-leads" role="tabpanel" aria-labelledby="all-leads-tab">
  <div class="responsiveTable">
    <table class="table table-bordered table-hover" id="AllLeadsTable">
      <thead>
        <tr class="filter-row">
          <th colspan="7">
            <div class="form-group">
              <input class="form-control small" type="text" id="filter-allLeadsTable" name=""  placeholder="Start typing to filter by keyword..." aria-label="" />
            </div>
          </th>
        </tr>
        <tr>
          <th>Name</th>
          <th>Priority</th>
          <th>Last Contact</th>
          <th>Status</th>
          <th>Contact Info</th>
          <th>Tasks</th>
          <th>Lead Created</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'active_leads_table_lead', collection: leads, as: :lead %>
      </tbody>
    </table>
  </div>
</div>

<script>
  filterTableRows('AllLeadsTable', [1,3,4,5,7])
</script>

app/views/home/_active_leads_my_leads.html.erb
<div class="active-leads-pane tab-pane fade" id="my-leads" role="tabpanel" aria-labelledby="my-leads-tab">
  <div class="responsiveTable">
    <table class="table table-bordered table-hover" id="MyLeadsTable">
      <thead>
        <tr class="filter-row">
          <th colspan="7">
            <div class="form-group">
              <input class="form-control small" type="text" id="filter-myLeadsTable" name=""  placeholder="Start typing to filter by keyword..." aria-label="" />
            </div>
          </th>
        </tr>
        <tr>
          <th>Name</th>
          <th>Priority</th>
          <th>Last Contact</th>
          <th>Status</th>
          <th>Contact Info</th>
          <th>Tasks</th>
          <th>Lead Created</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'active_leads_table_lead', collection: leads, as: :lead %>
      </tbody>
    </table>
  </div>
</div>

<script>
  filterTableRows('MyLeadsTable', [1,3,4,5,7])
</script>

app/views/home/_active_leads_stale_leads.html.erb
<div class="active-leads-pane tab-pane fade" id="stale-leads" role="tabpanel" aria-labelledby="stale-leads-tab">
  <div class="responsiveTable">
    <table class="table table-bordered table-hover" id="StaleLeadsTable">
      <thead>
        <tr class="filter-row">
          <th colspan="7">
            <div class="form-group">
              <input class="form-control small" type="text" id="filter-staleLeadsTable" name=""  placeholder="Start typing to filter by keyword..." aria-label="" />
            </div>
          </th>
        </tr>
        <tr>
          <th>Name</th>
          <th>Priority</th>
          <th>Last Contact</th>
          <th>Status</th>
          <th>Contact Info</th>
          <th>Tasks</th>
          <th>Lead Created</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'active_leads_table_lead', collection: leads, as: :lead %>
      </tbody>
    </table>
  </div>
</div>
<script>
  filterTableRows('StaleLeadsTable', [1,3,4,5,7])
</script>

app/views/home/_dashboard_v1.html.erb
<div class="row">
  <!-- Left Column -->
  <div class="col-md-12">
    <%= render partial: "today" %>
    <%= render partial: "upcoming", locals: {scheduled_actions: @upcoming_actions} %>
  </div>
  <!-- End Left Column -->

  <!-- Right Column -->
  <!-- End Right Column -->
</div>
<div class="row">
  <div class="col-md-12">
    <%= render partial: 'my_leads' %>
    <%#= render partial: 'my_property_leads' %>
    <%= render partial: 'waitlist' %>
    <%#= render partial: 'my_team' %>
    <%#= render partial: 'stats' %>
  </div>

</div>

app/views/home/_lead.html.erb
<div class="lead-row" id="open_lead_<%= lead.id %>">
  <div class="lead-row__actions">
    <% if lead.open? && policy(lead).permitted_state_events.any? %>
      <%= form_with(url: trigger_state_event_lead_path(id: lead.id, eventid: 'work'), method: 'post', local: true, class: 'lead-row__form' ) do %>
        <%= submit_tag('Work', class: "btn btn--primary btn--small", id: "lead-work-button")%>
      <% end %>
    <% end %>
  </div>
  <div class="lead-row__content">
    <%= render partial: "leads/lead_card", locals: {lead: lead} %>
  </div>
</div>

app/views/home/_my_property_leads.html.erb
<div class="section section--property-leads" id="dashboard_my_leads">
  <div class="section-header">
    <div class="section-header__content">
      <div class="section-header__icon">
        <%= glyph(:person) %>
      </div>
      <h3 class="section-header__title">
        Property Leads
      </h3>
    </div>
  </div>
  
  <% if current_user.property.present? %>
    <div class="section__stats">
      <div class="section__stats-item">
        <span class="section__stats-value">
          <%= current_user.property.leads.early_pipeline.count %> Active Leads
        </span>
      </div>
      <div class="section__stats-actions">
        <%= link_to("More...", search_leads_path({lead_search: {property_ids: [current_user.property.id], states: %w{open prospect showing application} }}), class: "btn btn--xs btn--primary") %>
        <%= link_to("Duplicates", duplicate_leads_property_path(id: current_user.property), class: "btn btn--xs btn--primary") %>
      </div>
    </div>
  <% end %>
  
  <div class="section__content">
    <% if current_user.property.present? && current_user.property.leads.in_progress.high_priority.any? %>
      <table class="data-table">
        <tbody class="data-table__body">
          <% current_user.property.leads.in_progress.high_priority.each do |lead| %>
            <tr>
              <td width="70%">
                <span class="lead-row__name"> <%= link_to(lead.name, lead_path(lead)) %> </span>
                <% if lead.property.present? %>
                  for <span class="u-text--nowrap"><%= link_to(lead.property.name, property_path(lead.property)) %></span>
                <% end %>
                <%= render partial: "leads/contact_mini_card", locals: {lead: lead} %>
              </td>
              <td>
                <%= lead_state_label(lead) %>
                <%= lead_priority_icon(lead) %>
                <br>
                <%= glyph(:question_sign) %> <%= short_datetime(lead.first_comm) %>
                <br>
                <%= glyph(:comment) %> <%= short_datetime(lead.last_comm) %>
                <br>
                <%= glyph(:task) %> <%= link_to(lead.scheduled_actions.incomplete.count, lead_path(id: lead.id, anchor: 'scheduled_actions'), class: "badge badge--primary") %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="empty-state empty-state--compact">
        <div class="empty-state__icon">
          <%= glyph(:person) %>
        </div>
        <% if current_user.property.present? %>
          <p class="empty-state__text">No high priority leads</p>
          <p class="empty-state__text empty-state__text--sm text-muted">High priority leads will appear here</p>
        <% else %>
          <p class="empty-state__text">No property assigned</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/_my_tasks.html.erb
<div class="greybox">

  <h4>
    <%= inline_svg_tag('list-check.svg', height: '20px') %>
    Tasks
  </h4>

  <div class="task-pills">
    <div class="btn-group">
      <%= link_to "My Tasks", "#", class: "btn btn-primary active", "aria-current": "page", id: "MyTasks-button", "data-showhide": "tasks" %>
      <%= link_to "All Tasks", "#", class: "btn btn-primary", id: "TeamTasks-button", "data-showhide": "tasks" %>
    </div>
  </div>

  <div class="dashboard-tasks g-0" id="MyTasks" data-showhide="tasks">
    <% service.my_tasks.each do |task| %>
      <%= my_task_icon(task) %>
    <% end %>
  </div>
  <div></div>

  <div class="dashboard-tasks g-0 d-none" id="TeamTasks" data-showhide="tasks">
    <% service.all_tasks.each do |task| %>
      <%= my_task_icon(task) %>
    <% end %>
  </div>

</div>

app/views/home/_my_team.html.erb
<div class="section section--team" id="dashboard_my_team">
  <div class="section-header">
    <div class="section-header__content">
      <div class="section-header__icon">
        <%= glyph(:person) %>
      </div>
      <h3 class="section-header__title">
        <%= current_user.team&.name %>
      </h3>
    </div>
  </div>
  
  <div class="section__content">
    <div class="quicklinks__grid">
      <% ( (current_user.properties.to_a) + ( current_user.team&.properties || [] ) ).flatten.uniq.each do |property| %>
        <% leads_accessible = policy(property).leads_accessible? %>
        <% if policy(property).show? %>
          <div class="quicklinks__card">
            <div class="quicklinks__card-header">
              <% if property.logo.attached? %>
                <%= link_to image_tag(property.logo.variant(resize: 'x30'), class: "quicklinks__logo"), property_path(property) %>
              <% else %>
                <h4 class="quicklinks__title"><%= link_to(property.name, property_path(property)) %></h4>
              <% end %>
            </div>
            
            <% if leads_accessible %>
              <div class="quicklinks__stats">
                <div class="quicklinks__stat-item">
                  <span class="quicklinks__stat-label">Mine:</span>
                  <%= link_to(property.leads.for_agent(current_user).count, search_leads_path({lead_search: {property_ids: [property.id], user_ids: [current_user.id]}}), class: "quicklinks__stat-value") %>
                </div>
                <div class="quicklinks__stat-item">
                  <span class="quicklinks__stat-label">Open:</span>
                  <%= link_to(property.leads.open.count, search_leads_path({lead_search: {property_ids: [property.id], states: ['open']}}), class: "quicklinks__stat-value") %>
                </div>
                <div class="quicklinks__stat-item">
                  <span class="quicklinks__stat-label">Active:</span>
                  <%= link_to(property.leads.active.count, search_leads_path({lead_search: {property_ids: [property.id], states: ['prospect', 'showing', 'application']}}), class: "quicklinks__stat-value") %>
                </div>
              </div>
              
              <div class="quicklinks__actions">
                <%= link_to('View Leads', search_leads_path({lead_search: {property_ids: [property.id]}}), class: "btn btn--xs btn--secondary") %>
                <% if policy(property).create_lead? %>
                  <%= link_to('Create', new_lead_path(property_id: property.id), class: "btn btn--xs btn--primary") %>
                <% end %>
                <%= link_to("Duplicates", duplicate_leads_property_path(id: property.id), class: "quicklinks__link") %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_stats.html.erb
<div class="col-md-12">
  <div class="row">
    <div class="col-md-12">
      <h3>
        <%= glyph(:stats) %>
        Stats
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <tbody>
          <tr>
            <td><strong>My Score</strong></td>
            <td><span class="badge"><%= current_user.total_score %></span></td>
          </tr>
          <tr>
            <td><strong>My Leads</strong></td>
            <td>
              <ul>
                <li>in Pipeline:  <%= current_user.leads.active.count %></li>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/_task.html.erb
<div class="task-icon">
  <a href="#!" class="link-urgent">
    <%= inline_svg_tag('calendar-days.svg') %>
  </a>
</div>
<div>
  <span class="task-appt-time">10/29 9:15AM</span><br>
  <a href="#!" class="link-urgent">Schedule Appointment</a><br>
  Bart Landry
</div>

app/views/home/_task_card.html.erb
<div class="card card--clickable card--status card--status-primary" data-href="<%= completion_form_scheduled_action_path(scheduled_action_card) %>">
  <div class="card__body">
    <div class="card__task-layout">
      <div class="card__icon card__icon--<%= scheduled_action_card.lead_action.try(:glyph) || 'primary' %>">
        <%= glyph(scheduled_action_card.lead_action.try(:glyph) || :list_alt) %>
      </div>
      
      <div class="card__details">
        <div class="card__meta">
          <%= glyph(:time) %>
          <%= short_datetime(scheduled_action_card.schedule.to_datetime) %>
        </div>
        
        <h4 class="card__title">
          <%= action_and_reason(scheduled_action_card) %>
        </h4>
        
        <% if scheduled_action_card.description.present? %>
          <p class="card__description">
            <%= scheduled_action_card.description %>
            <% unless scheduled_action_card.target == current_user %>
              <span class="u-text--primary">
                for <%= scheduled_action_card.target.name rescue '' %>
              </span>
            <% end %>
          </p>
        <% end %>
      </div>
      
      <div class="card__actions" onclick="event.stopPropagation();">
        <% if policy(scheduled_action_card).complete? %>
          <%= link_to(completion_form_scheduled_action_path(scheduled_action_card, event: 'complete'), 
                      class: 'btn btn--success btn--icon',
                      title: 'Complete Task',
                      data: { toggle: 'tooltip', placement: 'top' }) do %>
            <%= glyph(:ok) %>
          <% end %>
        <% end %>
        
        <% if policy(scheduled_action_card).edit? %>
          <%= link_to(edit_scheduled_action_path(scheduled_action_card), 
                      class: 'btn btn--primary btn--icon',
                      title: 'Edit Task',
                      data: { toggle: 'tooltip', placement: 'top' }) do %>
            <%= glyph(:pencil) %>
          <% end %>
        <% end %>
        
        <% if policy(scheduled_action_card).complete? %>
          <%= link_to(completion_form_scheduled_action_path(scheduled_action_card, event: 'reject'), 
                      class: 'btn btn--danger btn--icon',
                      title: 'Reject Task',
                      data: { toggle: 'tooltip', placement: 'top', confirm: 'Are you sure you want to reject this task?' }) do %>
            <%= glyph(:remove) %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_today.html.erb
<div id="dashboard_today" class="section section--today">
  <div class="section-header">
    <div class="section-header__content">
      <div class="section-header__icon">
        <%= glyph(:task) %>
      </div>
      <h3 class="section-header__title">Today</h3>
    </div>
  </div>

  <div class="section__content">
    <div class="leads-header">
      <div class="leads-header__info">
        <span class="u-text--nowrap badge">
          <% lead_text = @open_leads.count == 1 ? "Lead" : "Leads" %>
          <% if @limit_leads != @open_leads.count %>
            <%= @limit_leads %> of
            <%= @open_leads.count %> Open <%= lead_text %>
          <% else %>
            <%= @open_leads.count %> Open <%= lead_text %>
          <% end %>
        </span>
        <% if @open_leads.count > 0 && policy(Lead).mass_assignment? %>
          <%= tooltip_block('leads-mass-assign-link') do %>
            <%= link_to("Assign...", mass_assignment_leads_path, class: "btn btn--primary btn--small") %>
          <% end %>
        <% end %>
        <% if @limit_leads != @open_leads.count %>
          <% search_params = { states: ['open'] } %>
          <% search_params[:property_ids] = [@current_property.id] if @current_property.present? %>
          <%= link_to("Show All", search_leads_path(lead_search: search_params), class: "btn btn--primary btn--small") %>
        <% end %>
      </div>
    </div>

    <div class="lead-list" id="open_lead_listing">
      <%= render collection: @open_leads.limit(@limit_leads), partial: 'lead' %>
    </div>
    
    <% if @today_actions.any? %>
      <div class="tasks-section">
        <div class="section-header section-header--info">
          <div class="section-header__content">
            <div class="section-header__icon">
              <%= glyph(:time) %>
            </div>
            <h3 class="section-header__title">
              Tasks Due Today
              <span class="section-header__count"><%= @today_actions.count %></span>
            </h3>
            <% if @today_actions.count > 20 %>
              <div class="section-header__actions">
                <%= link_to "View All", scheduled_actions_path(team: true), class: "btn btn--primary btn--small" %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div class="tasks-list">
          <%= render collection: @today_actions.limit(20), partial: 'home/task_card', as: :scheduled_action_card, locals: { task_type: 'today' } %>
        </div>
      </div>
    <% elsif @open_leads.empty? %>
      <div class="empty-state empty-state--compact">
        <div class="empty-state__icon empty-state__icon--success">
          <%= glyph(:ok) %>
        </div>
        <p class="empty-state__text">All caught up! No leads or tasks for today.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/home/_unclaimed_leads.html.erb
<div class="responsiveTable">
  <table class="table table-bordered table-hover" id="UnclaimedLeadsTable">
    <thead>
      <th>Date/Time</th>
      <th>Name</th>
      <th>Contact Info</th>
      <th></th>
      <th>Assign</th>
    </thead>
    <tbody>
      <%= render collection: leads, partial: 'unclaimed_lead', as: :lead %>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<div class="dashboard">
  <div class="dashboard__container">
    <div class="section">
      <div class="section__content u-text--center">
        <h1 class="u-text--dark">Bluesky Lead Management</h1>
        <p class="u-text--lg u-text--muted">
          Welcome to Bluesky! Please Log in!
        </p>
        <div class="u-spacing--xl">
          <%= image_tag('under_construction.gif', title: 'Nostalgia') %>
        </div>
      </div>
    </div>
  </div>
</div>