config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount ActionCable.server => '/cable'
  authenticated :user, -> user { user.admin? }  do
    mount Flipflop::Engine => "/flipflop"
    mount DelayedJobWeb, at: "/delayed_job"
  end

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    confirmations: 'users/confirmations',
                                    unlocks: 'users/unlocks',
                                    passwords: 'users/passwords' }

  authenticated do
    root to: "home#dashboard", as: :authenticated_root
  end

  root to: redirect('/users/sign_in')

  get 'v2', to: 'home#design2'

  get '/home', to: 'home#dashboard'

  namespace :api do
    namespace :v1 do
      get 'referral_bounces/refer'
      get 'docs/swagger.:format', to: "swagger#index"
      get 'docs', to: "swagger#apidocs"
      resources :leads, only: [:index, :create ]
      get 'leads/prospect_stats', to: "leads#prospect_stats"
      get 'property_info', to: "leads#property_info"
      get 'property_schedule_availability.:format', to: "leads#property_schedule_availability"
      resources :messages, only: [:create]
    end
  end

  resources :scheduled_actions do
    collection do
      get :conflict_check, to: 'scheduled_actions#conflict_check'
      get 'update_scheduled_action_form_on_action_change', to: 'scheduled_actions#update_scheduled_action_form_on_action_change'
      get 'load_notification_template', to: 'scheduled_actions#load_notification_template'
    end
    member do
      post 'complete', to: 'scheduled_actions#complete'
      get 'completion_form', to: 'scheduled_actions#completion_form'
    end
  end

  resources :lead_actions
  resources :lead_referral_sources
  resources :articles
  resources :notes
  resources :reasons
  resources :roles
  resources :unit_types
  resources :units
  resources :users do
    member do
      post 'switch_setting', to: 'users#switch_setting'
    end
  end
  resources :residents
  resources :engagement_policies

  resources :properties do
    resources :units
    resources :unit_types
    resources :residents
    resource :messages, controller: 'property_messages', only: [:edit, :update] do
      member do
        post 'preview_sms'
        post 'preview_email'
      end
    end
    collection do
      post 'select_current', to: 'properties#select_current'
    end
    member do
      get 'duplicate_leads', to: 'properties#duplicate_leads'
      get 'user_stats', to: 'properties#user_stats'
    end
  end

  resources :leads do
    collection do
      get 'new/:entry', to: 'leads#new', as: 'custom_new'
      get 'search', to: "leads#search"
      get 'status_dashboard', to: "leads#status_dashboard"
      get 'mass_assignment', to: 'leads#mass_assignment'
      post 'mass_assign', to: 'leads#mass_assign'
    end
    member do
      post 'trigger_state_event', to: "leads#trigger_state_event"
      post 'mark_messages_read', to: "leads#mark_messages_read"
      get 'progress_state', to: "leads#progress_state"
      post 'update_state', to: "leads#update_state"
      get 'update_referrable_options', to: 'leads#update_referrable_options'
      post 'resend_sms_opt_in_message', to: 'leads#resend_sms_opt_in_message'
      post 'update_from_remote', to: 'leads#update_from_remote'
    end
    resources :messages do
      post 'deliver', on: :member
      post 'mark_read', on: :member
      post 'lead_page_mark_read', on: :member
    end
    resources :roommates
  end

  resources :lead_sources do
    post 'reset_token', on: :member
  end

  resources :messages do
    post 'deliver', on: :member
    post 'mark_read', on: :member
    get 'body_preview', on: :member
  end

  resources :message_templates

  resources :marketing_sources do
    resources :marketing_expenses
    collection do
      get 'form_suggest_tracking_details', to: 'marketing_sources#form_suggest_tracking_details'
      get 'report', to: 'marketing_sources#report'
    end
  end

  namespace :stats do
    get 'manager', to: 'manager'
    get 'report_csv', to: 'report_csv'
    get 'lead_engagement_csv', to: 'lead_engagement_csv'
    get 'referral_bounces', to: 'referral_bounces'
  end

  namespace :home do
    get 'manager_dashboard', to: 'manager_dashboard'
    get 'dashboard', to: 'dashboard'
    get 'insert_open_lead', to: 'insert_open_lead'
    post 'impersonate', to: 'impersonate'
    post 'end_impersonation', to: 'end_impersonation'
  end

  resources :teams do
    member do
      post 'add_member', to: 'add_member'
    end
  end

  get '/messaging/preferences', to: 'home#messaging_preferences', as: 'messaging_preferences'
  post '/messaging/unsubscribe', to: 'home#unsubscribe', as: 'messaging_unsubscribe'

end

app/models/resident.rb
# == Schema Information
#
# Table name: residents
#
#  id          :uuid             not null, primary key
#  lead_id     :uuid
#  property_id :uuid
#  unit_id     :uuid
#  residentid  :string
#  status      :string
#  dob         :date
#  title       :string
#  first_name  :string
#  middle_name :string
#  last_name   :string
#  address1    :string
#  address2    :string
#  city        :string
#  state       :string
#  zip         :string
#  country     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Resident < ApplicationRecord
  ### Class Concerns/Extensions
  audited

  ### Constants
  ALLOWED_PARAMS = [:lead_id, :property_id, :unit_id, :status, :dob, :title, :first_name, :middle_name, :last_name, :address1, :address2, :city, :state, :zip, :country]
  INVALID_UNIT_PROPERTY_ERROR = "Unit must belong to same Property"
  STATUS_OPTIONS = ["current", "former"]

  ### Associations
  belongs_to :lead, optional: true
  belongs_to :property
  belongs_to :unit
  has_one :detail, class_name: 'ResidentDetail', dependent: :destroy
  accepts_nested_attributes_for :detail
  has_many :lead_referrals, as: :referrable

  ### Validations
  validates :first_name, :last_name,
    presence: true
  validates :residentid,
    presence: true, uniqueness: {case_sensitive: false}
  validates :status,
    presence: true, inclusion: {in: STATUS_OPTIONS}
  validate :unit_belongs_to_property

  ### Callbacks
  #after_initialize :assign_detail
  before_validation :assign_residentid

  ### Class Methods

  def self.generate_residentid
    return "R%s" % Array.new(8){rand(10)}.join
  end

  def self.current
    where(status: 'current')
  end

  ### Instance Methods

  def name
    [title, first_name, middle_name, last_name].compact.join(" ")
  end

  def salutation
    [title, last_name].join(" ")
  end

  def name_and_unit
    "#{name} (#{unit&.name || '?'})"
  end

  private

  def unit_belongs_to_property
    return unless unit.present?
    if unit.property_id != property_id
      errors.add(:base, INVALID_UNIT_PROPERTY_ERROR)
    end
  end

  def assign_residentid
    self.residentid ||= Resident.generate_residentid
  end

  def assign_detail
    self.detail ||= ResidentDetail.new
  end


end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_resident, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /residents
  # GET /residents.json
  def index
    authorize Resident
    @residents = resident_scope.includes(:unit).order("units.unit ASC, residents.last_name ASC, residents.first_name ASC")
  end

  # GET /residents/1
  # GET /residents/1.json
  def show
    authorize @resident
  end

  # GET /residents/new
  def new
    @resident = resident_scope.new
    authorize @resident
  end

  # GET /residents/1/edit
  def edit
    authorize @resident
  end

  # POST /residents
  # POST /residents.json
  def create
    @resident = resident_scope.new
    authorize @resident
    @resident.attributes = resident_params

    respond_to do |format|
      if @resident.save
        format.html { redirect_to @resident, notice: 'Resident was successfully created.' }
        format.json { render :show, status: :created, location: @resident }
      else
        format.html { render :new }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residents/1
  # PATCH/PUT /residents/1.json
  def update
    authorize @resident
    respond_to do |format|
      if @resident.update(resident_params)
        format.html { redirect_to @resident, notice: 'Resident was successfully updated.' }
        format.json { render :show, status: :ok, location: @resident }
      else
        format.html { render :edit }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residents/1
  # DELETE /residents/1.json
  def destroy
    authorize @resident
    @resident.destroy
    respond_to do |format|
      format.html { redirect_to residents_url, notice: 'Resident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resident
      @resident = resident_scope.find(params[:id])
    end

    def resident_scope
      default_skope = policy_scope(Resident)
      if params[:override_scope]
        return default_skope
      else
        @property.present? ? @property.residents : default_skope
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resident_params
      params.require(:resident).permit(policy(Resident).allowed_params)
    end
end

app/helpers/residents_helper.rb
module ResidentsHelper
  def select_resident_status(val)
    options_for_select(Resident::STATUS_OPTIONS.map{|o| [o.capitalize, o]}, val)
  end
end

app/views/residents/_detail_form.html.erb
<%= form.fields_for :detail do  |detail_form| %>
  <%= detail_form.hidden_field :id %>
  <div class="fieldset-content">
    <fieldset>
      <legend>Details</legend>

      <div class="row">
        <div class="col-md-3 form__group">
          <%= detail_form.label :phone1, class: 'form__label' %>
          <%= detail_form.text_field :phone1, class: "form__control" %>
        </div>
        <div class="col-md-3 form__group">
          <%= detail_form.label :phone1_type, class: 'form__label' %>
          <%= detail_form.select :phone1_type, options_for_select(ResidentDetail::PHONE_TYPES), {include_blank: true}, { class: "form__control" } %>
        </div>
        <div class="col-md-3 form__group">
          <%= detail_form.label :phone1_tod, "Best Time to Call", class: 'form__label' %>
          <%= detail_form.select :phone1_tod, options_for_select(ResidentDetail::PHONE_TOD), {include_blank: true}, { class: "form__control" } %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-3 form__group">
          <%= detail_form.label :phone2, class: 'form__label' %>
          <%= detail_form.text_field :phone2, class: "form__control" %>
        </div>
        <div class="col-md-3 form__group">
          <%= detail_form.label :phone2_type, class: 'form__label' %>
          <%= detail_form.select :phone2_type, options_for_select(ResidentDetail::PHONE_TYPES), {include_blank: true}, { class: "form__control" } %>
        </div>
        <div class="col-md-3 form__group">
          <%= detail_form.label :phone2_tod, "Best Time to Call", class: 'form__label' %>
          <%= detail_form.select :phone2_tod, options_for_select(ResidentDetail::PHONE_TOD), {include_blank: true}, { class: "form__control" } %>
        </div>
      </div>

      <div class="row">
        <div class="form__group col-md-6">
          <%= detail_form.label :email, class: 'form__label' %>
          <%= detail_form.text_field :email, {class: "form__control"} %>
        </div>
      </div>

      <div class="row">
        <div class="form__group col-md-6">
          <%= detail_form.label :ssn, "SSN", class: 'form__label' %>
          <%= detail_form.text_field :ssn, {class: "form__control"} %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 form__group">
          <%= detail_form.label :id_number, "DL/ID Number", class: 'form__label' %>
          <%= detail_form.text_field :id_number, class: "form__control" %>
        </div>
        <div class="col-md-2 form__group">
          <%= detail_form.label :id_state, "DL/ID State", class: 'form__label' %>
          <%= detail_form.select :id_state, options_for_select(US_STATES), {include_blank: true}, { class: "form__control" } %>
        </div>
      </div>

    </fieldset>
  </div>
<% end %>

app/views/residents/_form.html.erb
<%= form_with(model: resident, local: true) do |form| %>
  <% if resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

      <ul>
        <% resident.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="fieldset-content">
    <fieldset>
      <legend>Property</legend>
      <div class="row">
        <div class="form__group col-md-4">
          <%= form.label :property_id %>
          <%= form.select :property_id, select_property(@resident.property_id), {include_blank: true}, { id: :resident_property_id, class: "form__control" } %>
        </div>
        <div class="form__group col-md-4">
          <%= form.label :unit_id %>
          <%= form.select :unit_id, select_unit(property: @resident.property, val: @resident.unit_id), {include_blank: true}, { id: :resident_unit_id, class: "form__control" } %>
        </div>
        <div class="form__group col-md-4">
          <%= form.label :status %>
          <%= form.select :status, select_resident_status(@resident.status), {}, id: :resident_status, class: "form__control" %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Address</legend>
      <div class="row">
        <div class="form__group col-md-2">
          <%= form.label :title %>
          <%= form.select :title, titles_for_select(@resident.title), {include_blank: true}, {id: :resident_title, class: "form__control"} %>
        </div>
        <div class="form__group col-md-4">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, id: :resident_first_name, class: "form__control" %>
        </div>
        <div class="form__group col-md-2">
          <%= form.label :middle_name %>
          <%= form.text_field :middle_name, id: :resident_middle_name, class: "form__control" %>
        </div>
        <div class="form__group col-md-4">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, id: :resident_last_name, class: "form__control" %>
        </div>
      </div>

      <div class="row">
        <div class="form__group col-md-12">
          <%= form.label :address1 %>
          <%= form.text_field :address1, id: :resident_address1, class: "form__control" %>
        </div>
      </div>

      <div class="row">
        <div class="form__group col-md-12">
          <%= form.label :address2 %>
          <%= form.text_field :address2, id: :resident_address2, class: "form__control" %>
        </div>
      </div>

      <div class="row">
        <div class="form__group col-md-4">
          <%= form.label :city %>
          <%= form.text_field :city, id: :resident_city, class: "form__control" %>
        </div>
        <div class="form__group col-md-2">
          <%= form.label :state %>
          <%= form.text_field :state, id: :resident_state, class: "form__control" %>
        </div>
        <div class="form__group col-md-2">
          <%= form.label :zip %>
          <%= form.text_field :zip, id: :resident_zip, class: "form__control" %>
        </div>
        <div class="form__group col-md-4">
          <%= form.label :country %>
          <%= form.text_field :country, id: :resident_country, class: "form__control" %>
        </div>
      </div>

    </fieldset>
  </div>

  <%= render partial: "detail_form", locals: {form: form} %>

  <div class="form__group">
    <button type="submit" class="btn btn--primary">Save</button>
  </div>
<% end %>

app/views/residents/edit.html.erb
<section class="section">
  <div class="row">
  <div class="col-md-12">
    <h1>Edit Resident</h1>
    <%= render 'form', resident: @resident %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= link_to 'Back', residents_path  %>
  </div>
</div>
</section>

app/views/residents/index.html.erb
<section class="section">
<div class="row">
  <div class="col-md-6">
    <% if @property.present? %>
      <h2><%= @property.name %></h2>
    <% end %>
    <h1>Residents</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table id="residents-table" class="table" data-clickable-rows="true">
        <thead>
          <tr>
            <th>Resident ID</th>
            <th>Status</th>
            <th>Name</th>
            <th>Property</th>
            <th>Unit</th>
            <th>Contact</th>
            <th class="text-right">Actions</th>
          </tr>
        </thead>
      <tbody>
        <% @residents.each do |resident| %>
          <tr>
            <td><%= resident.residentid %></td>
            <td><%= resident.status.try(:capitalize) %></td>
            <td><%= link_to(resident.name, property_resident_path(resident.property, resident)) %></td>
            <td><%= link_to(resident.property.name, property_path(resident.property)) %></td>
            <td><%= link_to(resident.unit.unit, property_unit_path(resident.property, resident.unit)) %></td>
            <td>
              <p>
                <% if resident.detail.phone1.present? %>
                  <span><%= glyph(:phone) %> <%= resident.detail.phone1 %></span><br/>
                <% end %>
                <% if resident.detail.phone2.present? %>
                  <span><%= glyph(:phone) %> <%= resident.detail.phone2 %></span><br/>
                <% end %>
                <% if resident.detail.email.present? %>
                  <span><%= glyph(:email) %> <%= resident.detail.email %></span>
                <% end %>
              </p>
            </td>
            <td class="actions">
              <%= link_to property_resident_path(resident.property, resident), class: "btn btn--icon btn--xs btn--ghost", title: "View" do %><%= glyph(:show) %><% end %>
              <%= link_to edit_property_resident_path(resident.property, resident), class: "btn btn--icon btn--xs btn--primary", title: "Edit" do %><%= glyph(:pencil) %><% end %>
              <%= link_to resident, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn--icon btn--xs btn--danger", title: "Delete" do %><%= glyph(:delete) %><% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>
</div>
</section>

app/views/residents/new.html.erb
<section class="section">
<div class="row">
  <div class="col-md-12">
    <h1>New Resident</h1>
    <%= render 'form', resident: @resident %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= link_to 'Back', residents_path  %>
  </div>
</div>
</section>

app/views/residents/show.html.erb
<section class="section">
<div class="row">
  <div class="col-md-10">

    <div class="row">
      <div class="col-md-6">
        <h1>Resident</h1>
        <h2><%= @resident.name %></h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <p>
          <strong>Resident ID: </strong>
          <%= @resident.residentid %>
        </p>
        <% if @resident.lead.present? %>
          <p>
            <strong>Lead: </strong>
            <%= link_to(@resident.name, lead_path(id: @resident.lead.id)) %>
          </p>
        <% end %>
        <p>
          <strong>Status: </strong>
          <%= @resident.status.try(:capitalize) %>
        </p>
        <p>
          <strong>Property: </strong>
          <%= @resident.property.name %>
        </p>
        <p>
          <strong>Unit: </strong>
          <%= @resident.unit.unit %>
        </p>
       </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <strong>Title: </strong>
        <%= @resident.title %>
      </div>
      <div class="col-md-3">
        <strong>First Name: </strong>
        <%= @resident.first_name %>
      </div>
      <div class="col-md-3">
        <strong>Middle Name: </strong>
        <%= @resident.middle_name %>
      </div>
      <div class="col-md-3">
        <strong>Last Name: </strong>
        <%= @resident.last_name %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <strong>Address1: </strong>
        <%= @resident.address1 %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <strong>Address2: </strong>
        <%= @resident.address2 %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <strong>City: </strong>
        <%= @resident.city %>
      </div>
      <div class="col-md-2">
        <strong>State: </strong>
        <%= @resident.state %>
      </div>
      <div class="col-md-2">
        <strong>Zip: </strong>
        <%= @resident.zip %>
      </div>
      <div class="col-md-2">
        <strong>Country: </strong>
        <%= @resident.country %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <strong>Phone 1: </strong>
        <%= @resident.detail&.phone1 %>
      </div>
      <div class="col-md-3">
        <strong>Type: </strong>
        <%= @resident.detail&.phone1_type || '-' %>
      </div>
      <div class="col-md-4">
        <strong>Best Time to Call: </strong>
        <%= @resident.detail&.phone1_tod || '-' %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <strong>Phone 2: </strong>
        <%= @resident.detail&.phone2 %>
      </div>
      <div class="col-md-3">
        <strong>Type: </strong>
        <%= @resident.detail&.phone2_type || '-' %>
      </div>
      <div class="col-md-4">
        <strong>Best Time to Call: </strong>
        <%= @resident.detail&.phone2_tod || '-' %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <strong>Email: </strong>
        <%= @resident.detail&.email %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-12">
        <strong>SSN: </strong>
        <%= @resident.detail&.ssn %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <strong>ID/DL Number: </strong>
        <%= @resident.detail&.id_number %>
      </div>
      <div class="col-md-3">
        <strong>ID State:</strong>
        <%= @resident.detail&.id_state %>
      </div>
    </div>

  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>Referrals</h3>
  </div>

  <% if @resident.lead_referrals.any? %>
    <ul>
      <% @resident.lead_referrals.order(created_at: :desc).each do |referral| %>
        <li>
          <span>
            Referred <%= link_to(referral.lead.name, referral.lead) %> to <%= referral.lead.property&.name || 'Unknown' %> on <%= long_date referral.created_at %>
          <br/>
          </span>
          <span class="small">
            <%= referral.note %>
          </span>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>None</p>
  <% end %>

</div>

<div class="row">
  <div class="col-md-4">
    <%= link_to 'Edit', edit_property_resident_path(@resident.property, @resident), class: "btn btn--primary" %>
    <%= link_to 'Back', property_residents_path(@resident.property), class: "btn btn--ghost" %>
  </div>
</div>
</section>